
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.MessageFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Windows XP
 */
public class utama extends javax.swing.JFrame {

    /**
     * Creates new form utama
     */
    public utama() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        txtNo = new javax.swing.JTextField();
        txtNama = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtJudul = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        txtDenda = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        rdpinjam = new javax.swing.JRadioButton();
        rdkembali = new javax.swing.JRadioButton();
        Pinjam = new com.toedter.calendar.JDateChooser();
        Kembali = new com.toedter.calendar.JDateChooser();
        rdpelajaran = new javax.swing.JRadioButton();
        rdkomik = new javax.swing.JRadioButton();
        rdnovel = new javax.swing.JRadioButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAlamat = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        btnAdd = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        Reset = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnPrint = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb1Data = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 0, 0));

        jLabel1.setFont(new java.awt.Font("Microsoft PhagsPa", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("FORM BIODATA PEMINJAMAN BUKU");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(667, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1310, 70));

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(txtNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 190, -1));
        jPanel2.add(txtNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 190, -1));

        jLabel10.setFont(new java.awt.Font("Urdu Typesetting", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("NO.ANGGOTA");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 17));

        jLabel11.setFont(new java.awt.Font("Urdu Typesetting", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("NAMA");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 49, 60, -1));

        jLabel12.setFont(new java.awt.Font("Urdu Typesetting", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("ALAMAT");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 93, 100, 20));

        jLabel13.setFont(new java.awt.Font("Urdu Typesetting", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("JENIS BUKU");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 195, 82, -1));

        jLabel15.setFont(new java.awt.Font("Urdu Typesetting", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("JUDUL BUKU");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 83, -1));
        jPanel2.add(txtJudul, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 250, 174, -1));

        jLabel16.setFont(new java.awt.Font("Urdu Typesetting", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("TANGGAL PINJAM");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, -1, -1));

        jLabel17.setFont(new java.awt.Font("Urdu Typesetting", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("TANGGAL KEMBALI");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, -1, -1));

        jLabel18.setFont(new java.awt.Font("Urdu Typesetting", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("DENDA");
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, 119, -1));
        jPanel2.add(txtDenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 400, 174, -1));

        jLabel19.setFont(new java.awt.Font("Urdu Typesetting", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("STATUS");
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 119, -1));

        buttonGroup2.add(rdpinjam);
        rdpinjam.setForeground(new java.awt.Color(255, 255, 255));
        rdpinjam.setText("PINJAM");
        jPanel2.add(rdpinjam, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 440, -1, -1));

        buttonGroup2.add(rdkembali);
        rdkembali.setForeground(new java.awt.Color(255, 255, 255));
        rdkembali.setText("KEMBALI");
        jPanel2.add(rdkembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 440, -1, -1));
        jPanel2.add(Pinjam, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 300, 174, -1));
        jPanel2.add(Kembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 350, 174, -1));

        buttonGroup1.add(rdpelajaran);
        rdpelajaran.setForeground(new java.awt.Color(255, 255, 255));
        rdpelajaran.setText("Pelajaran");
        jPanel2.add(rdpelajaran, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, -1, -1));

        buttonGroup1.add(rdkomik);
        rdkomik.setForeground(new java.awt.Color(255, 255, 255));
        rdkomik.setText("Komik");
        rdkomik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdkomikActionPerformed(evt);
            }
        });
        jPanel2.add(rdkomik, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 200, -1, -1));

        buttonGroup1.add(rdnovel);
        rdnovel.setForeground(new java.awt.Color(255, 255, 255));
        rdnovel.setText("Novel");
        jPanel2.add(rdnovel, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 200, -1, -1));

        txtAlamat.setColumns(20);
        txtAlamat.setRows(5);
        jScrollPane2.setViewportView(txtAlamat);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 187, 82));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 370, 500));

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAdd.setFont(new java.awt.Font("Century751 SeBd BT", 1, 14)); // NOI18N
        btnAdd.setText("SAVE");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });
        jPanel3.add(btnAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 22, 105, -1));

        btnDelete.setFont(new java.awt.Font("Century751 SeBd BT", 1, 14)); // NOI18N
        btnDelete.setText("DELETE");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        jPanel3.add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 22, -1, -1));

        Reset.setFont(new java.awt.Font("Century751 SeBd BT", 1, 14)); // NOI18N
        Reset.setText("CLEAR");
        Reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetActionPerformed(evt);
            }
        });
        jPanel3.add(Reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(329, 22, 102, -1));

        btnRefresh.setFont(new java.awt.Font("Century751 SeBd BT", 1, 14)); // NOI18N
        btnRefresh.setText("REFRESH");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });
        jPanel3.add(btnRefresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(449, 22, 113, -1));

        btnEdit.setFont(new java.awt.Font("Century751 SeBd BT", 1, 14)); // NOI18N
        btnEdit.setText("EDIT");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        jPanel3.add(btnEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 22, 109, -1));

        btnPrint.setFont(new java.awt.Font("Century751 SeBd BT", 1, 14)); // NOI18N
        btnPrint.setText("PRINT");
        btnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintActionPerformed(evt);
            }
        });
        jPanel3.add(btnPrint, new org.netbeans.lib.awtextra.AbsoluteConstraints(707, 22, 103, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 70, 940, 60));

        jPanel5.setBackground(new java.awt.Color(0, 0, 0));

        tb1Data.setBackground(new java.awt.Color(102, 102, 255));
        tb1Data.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "NoAnggota", "Nama", "Alamat", "JenisBuku", "JudulBuku", "TanggalPinjam", "TanggalKembali", "Denda", "Status"
            }
        ));
        tb1Data.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb1DataMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tb1Data);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 920, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 418, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 130, 940, 440));

        setBounds(0, 0, 1324, 609);
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String pinjam = dateFormat.format(Pinjam.getDate());
        String kembali = dateFormat.format(Kembali.getDate());        
        if ("".equals(txtNo.getText()) || "".equals(txtAlamat.getText()) ||
                "".equals(txtJudul.getText()) || "".equals(txtNama.getText()) || "".equals(txtDenda.getText()) || pinjam.equals("") || kembali.equals("")) {
            JOptionPane.showMessageDialog(this, "Harap Lengkapi Data", "Error", JOptionPane.WARNING_MESSAGE);
        }else{
            String JK = "";
            if (rdpinjam.isSelected()) {
                JK = "pinjam";
            }else {
                JK = "kembali";
            }
            String JB = "";
            if (rdpelajaran.isSelected()){
                JB = "Pelajaran";
            }
            else if (rdkomik.isSelected()){
                JB = "Komik";
            }
            else {
                JB = "Novel";
            }
                String SQL = "UPDATE tb_kembali SET "
                + "Nama='" + txtNama.getText()+"', Alamat='"+txtAlamat.getText()+"', " 
                        + "JenisBuku='"+JB+"', JudulBuku='"+txtJudul.getText()+"', TanggalPinjam='"+pinjam+"', TanggalKembali='"+kembali+"', Denda='"+txtDenda.getText()+"', "
                        + "Status='"+JK+"' "
                        + "WHERE NoAnggota='"+txtNo.getText()+"'";
                int status = KoneksiDB.execute(SQL);
                if(status == 1) {
                    JOptionPane.showMessageDialog(this, "Data berhasil update", "Sukses", JOptionPane.INFORMATION_MESSAGE);
                    selectData();
                }else{
                    JOptionPane.showMessageDialog(this, "Data gagal diupdate", "Sukses", JOptionPane.WARNING_MESSAGE);
                }
        }
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:
        selectData();
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void ResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetActionPerformed
        // TODO add your handling code here:
        txtNama.setText("");
        txtNo.setText("");
        txtJudul.setText("");
        buttonGroup1.clearSelection();
        txtDenda.setText("");
        buttonGroup2.clearSelection();
        Pinjam.setDate(null);
        Kembali.setDate(null);        
        txtAlamat.setText("");
    }//GEN-LAST:event_ResetActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        int baris = tb1Data.getSelectedRow();
        if (baris != -1) {
            String NoAnggota = tb1Data.getValueAt(baris, 0).toString();
            String SQL = "DELETE FROM tb_kembali WHERE NoAnggota='"+NoAnggota+"'";
            int status = KoneksiDB.execute(SQL);
            if (status==1) {
                JOptionPane.showMessageDialog(this, "Data berhasil dihapus", "Sukses", JOptionPane.INFORMATION_MESSAGE);
            }else{
                JOptionPane.showMessageDialog(this, "Data gagal dihapus", "Gagal", JOptionPane.WARNING_MESSAGE);
            }
        }else{
            JOptionPane.showMessageDialog(this, "Pilih Baris Data Terlebih dahulu", "Error", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String pinjam = dateFormat.format(Pinjam.getDate());
        String kembali = dateFormat.format(Kembali.getDate());        
        if ("".equals(txtNo.getText()) || "".equals(txtAlamat.getText()) ||
                "".equals(txtJudul.getText()) || "".equals(txtNama.getText()) || "".equals(txtDenda.getText()) || pinjam.equals("") || kembali.equals("")) {
            JOptionPane.showMessageDialog(this, "Harap Lengkapi Data", "Error", JOptionPane.WARNING_MESSAGE);
        }else {
            String JK = "";
            if (rdpinjam.isSelected()) {
                JK = "pinjam";
            }else {
                JK = "kembali";
            }
            String JB = "";
            if (rdpelajaran.isSelected()){
                JB = "Pelajaran";
            }
            else if (rdkomik.isSelected()){
                JB = "Komik";
            }
            else {
                JB = "Novel";
            }
            String SQL = "INSERT INTO tb_kembali (NoAnggota,Nama,Alamat,JenisBuku,JudulBuku,TanggalPinjam,TanggalKembali,Denda,Status) "
                    + "VALUES('"+txtNo.getText()+"','"+txtNama.getText()+"','"+txtAlamat.getText()+"',"
                    +"'"+JB+"','"+txtJudul.getText()+"','"+pinjam+"', '"+kembali+"','"+txtDenda.getText()+"','"+JK+"')";
              int status = KoneksiDB.execute(SQL);
              if (status == 1){
                  JOptionPane.showMessageDialog(this, "Data berhasil ditambahkan", "Sukses", JOptionPane.INFORMATION_MESSAGE);
                  selectData();
              }else{
                  JOptionPane.showMessageDialog(this, "Data gagal ditambahkan", "Sukses", JOptionPane.WARNING_MESSAGE);
              }
        } 
    }//GEN-LAST:event_btnAddActionPerformed

    private void tb1DataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb1DataMouseClicked
        // TODO add your handling code here:
        int baris = tb1Data.getSelectedRow();
        if (baris !=1) {
            txtNo.setText(tb1Data.getValueAt(baris, 0).toString());
            txtNama.setText(tb1Data.getValueAt(baris, 1).toString());
            txtAlamat.setText(tb1Data.getValueAt(baris, 2).toString());
            if ("pelajaran".equals(tb1Data.getValueAt(baris, 3).toString())){
                rdpelajaran.setSelected(true);
            }else if("komik".equals(tb1Data.getValueAt(baris, 3).toString())){
                rdkomik.setSelected(true);
            }else{
                rdnovel.setSelected(true);
            }            
            txtJudul.setText(tb1Data.getValueAt(baris, 4).toString());
            SimpleDateFormat date = new SimpleDateFormat("yyyy-MM-dd");
            Date dateFormat = null;
            try {
                dateFormat = date.parse(tb1Data.getValueAt(baris, 5).toString());
            } catch (ParseException ex) {
                java.util.logging.Logger.getLogger(utama.class.getName()).log(Level.SEVERE, null, ex);
            }
            Pinjam.setDate(dateFormat);           
            try {
                dateFormat = date.parse(tb1Data.getValueAt(baris, 6).toString());
            } catch (ParseException ex) {
                java.util.logging.Logger.getLogger(utama.class.getName()).log(Level.SEVERE, null, ex);
            }
            Kembali.setDate(dateFormat);
            txtDenda.setText(tb1Data.getValueAt(baris, 7).toString());
            if ("pinjam".equals(tb1Data.getValueAt(baris, 8).toString())){
                rdpinjam.setSelected(true);
            }else{
                rdkembali.setSelected(true);
            }                  
        }
    }//GEN-LAST:event_tb1DataMouseClicked

    private void btnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintActionPerformed
        // TODO add your handling code here:     
        MessageFormat header = new MessageFormat("Biodata Peminjaman Buku");
        MessageFormat footer = new MessageFormat("Page {0,number,integer}   ");
        try {
            tb1Data.print(JTable.PrintMode.FIT_WIDTH, header, footer, true, null, true, null);
        } catch (java.awt.print.PrinterException e) {
            System.err.format("Cannot print %s%n", e.getMessage());
        }
    }//GEN-LAST:event_btnPrintActionPerformed

    private void rdkomikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdkomikActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rdkomikActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new utama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser Kembali;
    private com.toedter.calendar.JDateChooser Pinjam;
    private javax.swing.JButton Reset;
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnPrint;
    private javax.swing.JButton btnRefresh;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButton rdkembali;
    private javax.swing.JRadioButton rdkomik;
    private javax.swing.JRadioButton rdnovel;
    private javax.swing.JRadioButton rdpelajaran;
    private javax.swing.JRadioButton rdpinjam;
    private javax.swing.JTable tb1Data;
    private javax.swing.JTextArea txtAlamat;
    private javax.swing.JTextField txtDenda;
    private javax.swing.JTextField txtJudul;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtNo;
    // End of variables declaration//GEN-END:variables

    private void selectData() {
        String kolom[] = {"NoAnggota","Nama","Alamat","JenisBuku","JudulBuku","TanggalPinjam","TanggalKembali","Denda","Status"};
        DefaultTableModel dtm = new DefaultTableModel(null, kolom);
        String SQL = "SELECT * FROM tb_kembali";
        ResultSet rs = KoneksiDB.executeQuery(SQL);
        try {
            while(rs.next()) {
                String NoAnggota = rs.getString(1);
                String Nama = rs.getString(2);
                String Alamat = rs.getString(3);
                String JenisBuku = "";
                if ("pelajaran".equals(rs.getString(4))){
                    JenisBuku = "pelajaran";
                }else if("komik".equals(rs.getString(4))){
                    JenisBuku = "komik";
                }else{
                    JenisBuku = "novel";
                }
                String JudulBuku = rs.getString(5);
                String TanggalPinjam = rs.getString(6);
                String TanggalKembali = rs.getString(7);
                String Denda = rs.getString(8);
                String Status = "";
                if ("pinjam".equals(rs.getString(9))) {
                    Status = "pinjam";
                }else{
                    Status = "kembali";
                }                
                String data[] = {NoAnggota,Nama,Alamat,JenisBuku,JudulBuku,TanggalPinjam,TanggalKembali,Denda,Status};
                dtm.addRow(data);
            }   
        } catch (SQLException ex) {
            java.util.logging.Logger.getLogger(utama.class.getName()).log(Level.SEVERE, null, ex);
        }
        tb1Data.setModel(dtm);
    }
}
